export const CREATE_NOTES_REQUEST = "CREATE_NOTES_REQUEST";
export const CREATE_NOTES_SUCCESS = "CREATE_NOTES_SUCCESS";
export const CREATE_NOTES_FAILURE = "CREATE_NOTES_FAILURE";

export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";

export const GET_NOTES_BYID_REQUEST = "GET_NOTES_BYID_REQUEST";
export const GET_NOTES_BYID_SUCCESS = "GET_NOTES_BYID_SUCCESS";
export const GET_NOTES_BYID_FAILURE = "GET_NOTES_BYID_FAILURE";

export const UPDATE_NOTES_BYID_REQUEST = "UPDATE_NOTES_BYID_REQUEST";
export const UPDATE_NOTES_BYID_SUCCESS = "UPDATE_NOTES_BYID_SUCCESS";
export const UPDATE_NOTES_BYID_FAILURE = "UPDATE_NOTES_BYID_FAILURE";

export const DELETE_NOTES_BYID_REQUEST = "DELETE_NOTES_BYID_REQUEST";
export const DELETE_NOTES_BYID_SUCCESS = "DELETE_NOTES_BYID_SUCCESS";
export const DELETE_NOTES_BYID_FAILURE = "DELETE_NOTES_BYID_FAILURE";